# Assignment _1
# Name : Patel Ayush (202318036)

##TASK_A

In [ ]:
#Q1 Block Matrix Multiplication

import numpy as np

def block(A,B):
	n1=len(A)
	n2=len(B[0])
	n3=len(A[0])
	C=[]
	for i in range(n1):
		list1=[]
		for j in range(n2):
			result=0
			for k in range(n3):
				result=result+ A[i][k]*B[k][j]
			list1.append(result)
		C.append(list1)
	return np.array(C)


def sub_mat(A,B):

  n = len(A)
  if n <= 2:
    return block(A, B)

  sub_mat_len_A=len(A)//2


  A1=A[0:sub_mat_len_A,0:sub_mat_len_A]

  A2=A[0:sub_mat_len_A,sub_mat_len_A:]

  A3=A[sub_mat_len_A:,0:sub_mat_len_A]

  A4=A[sub_mat_len_A:,sub_mat_len_A:]


  sub_mat_len_B=len(A)//2


  B1=B[0:sub_mat_len_B,0:sub_mat_len_B]

  B2=B[0:sub_mat_len_B,sub_mat_len_B:]

  B3=B[sub_mat_len_B:,0:sub_mat_len_B]

  B4=B[sub_mat_len_B:,sub_mat_len_B:]


  C1 = sub_mat(A1, B1) + sub_mat(A2, B3)
  C2 = sub_mat(A1, B2) + sub_mat(A2, B4)
  C3 = sub_mat(A3, B1) + sub_mat(A4, B3)
  C4 = sub_mat(A3, B2) + sub_mat(A4, B4)

  result = np.concatenate((np.concatenate((C1, C2), axis=1),np.concatenate((C3, C4), axis=1)), axis=0)
  return result

A = np.array([[1, 2, 3, 0], [4, 5, 6, 7], [7, 8, 9, 3], [1, 0, 3, 4]])
B = np.array([[3, 2, 1, 8], [9, 7, 8, 3], [6, 4, 5, 1], [6, 8, 1, 0]])

result =sub_mat(A, B)
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nResult:")
print(result)





Matrix A:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Matrix B:
[[ 6  5  4  3  2  1]
 [12 11 10  9  8  7]
 [18 17 16 15 14 13]
 [24 23 22 21 20 19]
 [30 29 28 27 26 25]
 [36 35 34 33 32 31]]

Result:
[[ 546  525  504  483  462  441]
 [1302 1245 1188 1131 1074 1017]
 [2058 1965 1872 1779 1686 1593]
 [2814 2685 2556 2427 2298 2169]
 [3570 3405 3240 3075 2910 2745]
 [4326 4125 3924 3723 3522 3321]]


##TASK_B

In [ ]:
#Q2 Using RapidAPI

import requests
import pandas as pd


def fetch_quotes():
    url = "https://famous-quotes4.p.rapidapi.com/random"
    querystring = {"category": "all", "count": "1000"}  # Change the count based on your requirement
    headers = {
        "X-RapidAPI-Key": "1266d2b196msh63df479e5e7f99dp181780jsn2495127cff68",
        "X-RapidAPI-Host": "famous-quotes4.p.rapidapi.com"
    }
    response = requests.get(url, headers=headers, params=querystring)
    data = response.json()
    df = pd.DataFrame(data)
    return df

dfs = [fetch_quotes() for i in range(50)]


final_df = pd.concat(dfs, ignore_index=True)

final_df



id                                               text  \
0      17676  Working with HBO was an opportunity to experie...   
1      75208  But the key to our marriage is the capacity to...   
2      51743         Everything in excess is opposed to nature.   
3       9679  Even if I know I shall never change the masses...   
4      46629  We busted a lot of family secrets with this. B...   
...      ...                                                ...   
49995   6824  It's impossible, I think, however much I'd bec...   
49996  21336  When I was 24, I was full of life. I was that ...   
49997  22162  A cheerful frame of mind, reinforced by relaxa...   
49998   6488  I was never one to patiently pick up broken fr...   
49999  45737  So long as men worship the Caesars and Napoleo...   

                      author    category  
0            Martin Scorsese  experience  
1             Michael J. Fox        work  
2                Hippocrates      nature  
3             Richard Wagner      change  
4              Kenny Loggins         mom  
...                      ...         ...  
49995   Christopher Hitchens        best  
49996  Jean Claude Van Damme      famous  
49997   George Matthew Adams        fear  
49998      Margaret Mitchell        best  
49999          Aldous Huxley         men  

[50000 rows x 4 columns]

##TASK_C

In [ ]:
#Using Webscraping (BeautifulSoup)

from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import time


In [ ]:
URL ='https://www.amazon.in/s?k=speaker'
webpage=requests.get(URL)
webpage


<Response [200]>

In [ ]:
soup = BeautifulSoup(webpage.content, 'lxml')

In [ ]:
product=soup.find_all('div',class_='puis-card-container s-card-container s-overflow-hidden aok-relative puis-include-content-margin puis puis-v1x9xtdrqwkf2b2sy3gv3bhvhpn s-latency-cf-section puis-card-border')

In [ ]:
len(product)

16

In [ ]:
#only fetch 1st page

name=[]
rating=[]
reviews=[]
price=[]
for i in product:
  name.append(i.find('h2').text.strip())
  rating.append(i.find('span',class_='a-icon-alt').text.strip())
  reviews.append(i.find('span',class_='a-size-base s-underline-text').text.strip())
  price.append(i.find('span',class_='a-price-whole').text.strip())

d={'product_name':name,'rating': rating,'reviews':reviews,'price':price}

df=pd.DataFrame(d)
df

product_name              rating  \
0   Zebronics ZEB-COUNTY 3W Wireless Bluetooth Por...  3.8 out of 5 stars   
1   amazon basics 2.0 Multimedia Speaker for PC | ...  4.3 out of 5 stars   
2   Tribit[Upgraded Version XSound Go 16W 5.0 Blue...  4.4 out of 5 stars   
3   boAt Stone 1000 14W Bluetooth Speaker with 8 H...  4.2 out of 5 stars   
4   boAt PartyPal 200/208 70W RMS Stereo Party Spe...  3.6 out of 5 stars   
5   JBL Go 2, Wireless Portable Bluetooth Speaker ...  4.3 out of 5 stars   
6   boAt Stone 1200 14W Bluetooth Speaker with Upt...  4.2 out of 5 stars   
7   Marshall Willen 10 W Portable Bluetooth Speake...  4.6 out of 5 stars   
8   [New]Sony SRS-XB100 Wireless Bluetooth Portabl...  4.0 out of 5 stars   
9   Philips Audio MMS2625B 32W 2.1 Channel Wireles...  4.0 out of 5 stars   
10  JBL Flip 5 Wireless Portable Bluetooth Speaker...  4.4 out of 5 stars   
11  Marshall Acton II 60 Watt Wireless Bluetooth S...  4.3 out of 5 stars   
12  Harman Kardon Aura Studio 3, Award Winning Tim...  4.4 out of 5 stars   
13  boAt Stone 1450 Portable Wireless Speaker with...  3.8 out of 5 stars   
14  boAt Stone 1450 Portable Wireless Speaker with...  3.8 out of 5 stars   
15  Bose Soundlink Micro Bluetooth Speaker: 5 Watt...  4.6 out of 5 stars   

   reviews   price  
0   60,791     549  
1   24,132     354  
2   11,420   2,799  
3   43,184   2,499  
4      278   6,999  
5   68,785   2,099  
6   17,116   3,999  
7    1,712   9,999  
8   18,592   4,490  
9   23,321   3,410  
10  34,182   7,999  
11   1,113  26,999  
12     229  27,999  
13   1,617   4,499  
14   1,617   4,499  
15  50,120  10,900

In [ ]:
#fecth as many pages as we provide i.e we have to provide the no_of_pages we want to scrape form the amazon website

def scrape_amazon(search_keyword, num_pages):
    base_url = 'https://www.amazon.in/s'
    data = []

    for page in range(1, num_pages + 1):
        params = {'k': search_keyword, 'page': page}
        webpage = requests.get(base_url, params=params)
        soup = BeautifulSoup(webpage.content, 'html.parser')

        products = soup.find_all('div', class_='puis-card-container s-card-container s-overflow-hidden aok-relative puis-include-content-margin puis puis-v1x9xtdrqwkf2b2sy3gv3bhvhpn s-latency-cf-section puis-card-border')

        for product in products:
            name = product.find('h2').text.strip()
            rating = product.find('span', class_='a-icon-alt').text.strip() if product.find('span', class_='a-icon-alt') else 'N/A'
            reviews = product.find('span', class_='a-size-base s-underline-text').text.strip() if product.find('span', class_='a-size-base s-underline-text') else 'N/A'
            price = product.find('span', class_='a-price-whole').text.strip() if product.find('span', class_='a-price-whole') else 'N/A'

            data.append({'product_name': name, 'rating': rating, 'reviews': reviews, 'price': price})
        time.sleep(2)
    return pd.DataFrame(data)

search_keyword = 'speaker'
num_pages_to_scrape = 50
df = scrape_amazon(search_keyword, num_pages_to_scrape)
print(df)


                                          product_name              rating  \
0    amazon basics 16W Bluetooth Soundbar Speaker w...  3.9 out of 5 stars   
1    Tribit MaxSound Plus 24W Bluetooth Wireless Sp...  4.3 out of 5 stars   
2    Infinity - JBL Clubz Mini, Wireless Ultra Port...  4.1 out of 5 stars   
3    Zebronics ZEB-COUNTY 3W Wireless Bluetooth Por...  3.8 out of 5 stars   
4    amazon basics 2.0 Multimedia Speaker for PC | ...  4.3 out of 5 stars   
..                                                 ...                 ...   
601                                             Tribit  4.4 out of 5 stars   
602                                             Tribit  4.5 out of 5 stars   
603                                            Krisons  4.0 out of 5 stars   
604                                             Tribit  4.4 out of 5 stars   
605                                               AJUK                 N/A   

    reviews   price  
0       559     899  
1     3,677   5,199

In [ ]:
df

product_name              rating  \
0    amazon basics 16W Bluetooth Soundbar Speaker w...  3.9 out of 5 stars   
1    Tribit MaxSound Plus 24W Bluetooth Wireless Sp...  4.3 out of 5 stars   
2    Infinity - JBL Clubz Mini, Wireless Ultra Port...  4.1 out of 5 stars   
3    Zebronics ZEB-COUNTY 3W Wireless Bluetooth Por...  3.8 out of 5 stars   
4    amazon basics 2.0 Multimedia Speaker for PC | ...  4.3 out of 5 stars   
..                                                 ...                 ...   
601                                             Tribit  4.4 out of 5 stars   
602                                             Tribit  4.5 out of 5 stars   
603                                            Krisons  4.0 out of 5 stars   
604                                             Tribit  4.4 out of 5 stars   
605                                               AJUK                 N/A   

    reviews   price  
0       559     899  
1     3,677   5,199  
2    33,915     898  
3    60,892     549  
4    24,133     354  
..      ...     ...  
601     178   7,999  
602   1,920  20,999  
603      49   1,899  
604  11,423   3,099  
605     N/A     999  

[606 rows x 4 columns]

In [ ]:
csv_path = r'C:\Speaker_dataset.csv'
df.to_csv(csv_path, index=True)